/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TrailsPostIdRouteImport } from './routes/trails/$postId'
import { Route as AccountTrailsIndexRouteImport } from './routes/account/trails/index'
import { Route as AccountTrailsAddIndexRouteImport } from './routes/account/trails/add/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsPostIdRoute = TrailsPostIdRouteImport.update({
  id: '/trails/$postId',
  path: '/trails/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTrailsIndexRoute = AccountTrailsIndexRouteImport.update({
  id: '/account/trails/',
  path: '/account/trails/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTrailsAddIndexRoute = AccountTrailsAddIndexRouteImport.update({
  id: '/account/trails/add/',
  path: '/account/trails/add/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trails/$postId': typeof TrailsPostIdRoute
  '/account': typeof AccountIndexRoute
  '/account/trails': typeof AccountTrailsIndexRoute
  '/account/trails/add': typeof AccountTrailsAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trails/$postId': typeof TrailsPostIdRoute
  '/account': typeof AccountIndexRoute
  '/account/trails': typeof AccountTrailsIndexRoute
  '/account/trails/add': typeof AccountTrailsAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trails/$postId': typeof TrailsPostIdRoute
  '/account/': typeof AccountIndexRoute
  '/account/trails/': typeof AccountTrailsIndexRoute
  '/account/trails/add/': typeof AccountTrailsAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trails/$postId'
    | '/account'
    | '/account/trails'
    | '/account/trails/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trails/$postId'
    | '/account'
    | '/account/trails'
    | '/account/trails/add'
  id:
    | '__root__'
    | '/'
    | '/trails/$postId'
    | '/account/'
    | '/account/trails/'
    | '/account/trails/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrailsPostIdRoute: typeof TrailsPostIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountTrailsIndexRoute: typeof AccountTrailsIndexRoute
  AccountTrailsAddIndexRoute: typeof AccountTrailsAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails/$postId': {
      id: '/trails/$postId'
      path: '/trails/$postId'
      fullPath: '/trails/$postId'
      preLoaderRoute: typeof TrailsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/trails/': {
      id: '/account/trails/'
      path: '/account/trails'
      fullPath: '/account/trails'
      preLoaderRoute: typeof AccountTrailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/trails/add/': {
      id: '/account/trails/add/'
      path: '/account/trails/add'
      fullPath: '/account/trails/add'
      preLoaderRoute: typeof AccountTrailsAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrailsPostIdRoute: TrailsPostIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountTrailsIndexRoute: AccountTrailsIndexRoute,
  AccountTrailsAddIndexRoute: AccountTrailsAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
